### ISSUE TITLE
Do something else with the video

### ISSUE THREAD

**Issue by arenciaga** [hilalbaig/HBRecorder#1]
How can I use the final video in any other view other than saving it in the camera roll

**Comment by hilalbaig** [comment]
When **HBRecorder** finish recording, you get video URL in **HBRecorder** delegate,
`- (void)recorder:( HBRecorder *  )recorder  didFinishPickingMediaWithUrl:(NSURL * )videoUrl;`
Use that videoUrl where ever you want.
