### ISSUE TITLE
Fade in Problem Between segments 

### ISSUE THREAD

**Issue by credo92** [hilalbaig/HBRecorder#3]
When i start recording , when i pause and record again several times and then export, 
I see a fadeIn ( the video gets blurred) just before when the next segment is going to start. How to remove this ? 

![img_0028](https://user-images.githubusercontent.com/9612194/29738194-df180d8e-89ea-11e7-9a2c-7befb20aa086.PNG)

**Comment by hilalbaig** [comment]
This is because you are recording video segments less then animationDuration.

**Comment by hilalbaig** [comment]
animationDuration Is HBTransition.h property which is set to 0.5s by default.

**Comment by hilalbaig** [comment]
Can you test it by recording a bit longer duration of each segments?

**Comment by credo92** [comment]
Yes, its working fine! thank you
