### ISSUE TITLE
Programmatically Pause a segment

### ISSUE THREAD

**Issue by credo92** [hilalbaig/HBRecorder#4]
Is there a way to Programmatically Pause the video? rather than tapping? 

I am unable to find some openings. Please help.

**Comment by hilalbaig** [comment]
Call pause function of recorder (HBRecorder)

**Comment by credo92** [comment]
-I want to Trigger the pause function at a specific time interval ( Time which is displayed on the top in the video recording ) 
-Like when the timer reaches 10  seconds - it should pause.
-So I extracted the else condition of (IBAction) shutterButtonTapped HBRecorder.m 

Like this:

`- (void)PauseTest
{
    [_recorder pause];
    //change UI
    [self.recBtn setImage:self.recStartImage
                 forState:UIControlStateNormal];
    printf("Recorder pause Tapped!");
}
`

Is there any opening to trigger the pause on a particular time interval of the recording using HBRecorder?

**Comment by hilalbaig** [comment]
Yes you can do it using maxRecordDuration property of HBRecorder. 
recorder.maxRecordDuration = 10;

It is shown in example project. Check example project for more information.

**Comment by credo92** [comment]
- Currently, Pause functionality for segments, is handled by the else condition of (IBAction) shutterButtonTapped in HBRecorder.m

- But My main point is to Pause the recording programmatically, a segment gets created, then user taps to start recording again and so next segment gets created.

-Yes, i already tried using maxRecordDuration but that didn't work since I want to pause automatically to create various segments of pre-defined duration.

For example, I wanted  4 segments of 
10sec ... 5 sec ... 5 sec ... 10 sec

- So That when the timer reaches a specific time interval like 10 sec, it should pause automatically, segments of 10 sec get created,  then user taps to start recording when the timer reaches 15 seconds, it pauses automatically, a segment of 5 sec gets created. 

Please help.

**Comment by hilalbaig** [comment]
So with maxRecordDuration we need maxSegmentDuration property as well, let me apply some quick tweaks to it. I will let you know.

**Comment by hilalbaig** [comment]
I have released [1.0.1](https://github.com/hilalbaig/HBRecorder/tree/1.0.1), `maxSegmentDuration` property added to `recorder`. Now you just need to set this property when presenting `HBRecorder` Controller like:
```
//Set segment max recording duration
recorder.maxSegmentDuration = 10;
```

**Comment by credo92** [comment]
-It works with the recorder.maxSegmentDuration 

- Can we pass an array of values [ 2, 4,6,7 ] where each element of the array represents a different segmentDuration? 

-Because am trying to give the recorder.maxSegmentDuration an array of values 
Like I am trying to do this :

var i : Int = 0
var arr: [Int] = [3,4,5,6,12]
for i in 0...arr.count {
            recorder?.maxSegmentDuration = Int64(arr[i]) 
}

But it gives me an error, "fatal error: Index out of range"


Please HELP!!

**Comment by hilalbaig** [comment]
Because maxSegmentDuration is int type not array type.

**Comment by credo92** [comment]
Yes I know that, but I wanted to know whether there is any scope or an opening to pass an array of segment durations. Please advise.

**Comment by credo92** [comment]
Created new issue for this. 

[https://github.com/hilalbaig/HBRecorder/issues/5](url)
